version: 2
updates:
  - package-ecosystem: pip
    directories:
    - /.github
    - /bench
    - /docs
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
